[package]
name = "imp-compiler"
version = "0.1.0"
edition.workspace = true

[dependencies]
imp-ast = { path = "../imp-ast" }
imp-ir = { path = "../imp-ir" }
imp-std = { path = "../imp-std" }

[lints]
workspace = true
