[package]
name = "imp-bytecode"
version = "0.1.0"
edition.workspace = true

[dependencies]
imp-ir = { path = "../imp-ir" }

[dev-dependencies]
imp-compiler = { path = "../imp-compiler" }
imp-vm = { path = "../imp-vm" }

[lints]
workspace = true
